spring:
  application:
    name: index-config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/AUGUSTRUSH8/test/
          searchPaths: repo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/